sonar.projectKey=lastmile-backend-ws
sonar.projectName=LastMile Backend WebSocket (Realtime)
sonar.projectVersion=1.0.0

# Para SonarCloud descomenta y pon el nombre de tu organización:
# sonar.organization=lastmileplatform

sonar.sources=src
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.spec.ts,\
  **/migrations/**,\
  **/main.ts,\
  **/*.module.ts,\
  **/*.dto.ts,\
  **/*.entity.ts

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.typescript.tsconfigPath=tsconfig.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=\
  **/migrations/**,\
  **/main.ts,\
  **/*.module.ts,\
  **/*.dto.ts,\
  **/*.entity.ts,\
  **/config/**

sonar.sourceEncoding=UTF-8
